# docker-compose.yml
version: '3.8'

services:
  rag-agent:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped